image: Visual Studio 2019  
environment:
  PYTHON: "C:\\Python39"  
  SIGNTOOL_PATH: "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.19041.0\\x64"  # Путь к signtool

install:
  - ps: |
      # Устанавливаем Python (если не установлен)
      if (-not (Test-Path $env:PYTHON)) {
          choco install python --version=3.9.0 --params="/InstallDir:$env:PYTHON"
      }
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pyinstaller

build_script:
  - pyinstaller --onefile zapret_updater.py

after_build:
  - ps: |
      # Проверяем, что файл существует
      if (Test-Path "dist\\zapret_updater.exe") {
          Write-Host "Файл zapret_updater.exe успешно создан."
      } else {
          Write-Host "Ошибка: Файл zapret_updater.exe не найден."
          exit 1
      }

artifacts:
  - path: dist\zapret_updater.exe
    name: zapret_updater.exe

test: off  
